services:
  postgres:
    image: postgres:16
    container_name: postgres_crud
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432" 